name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.0"
      - run: go get -t -d -v ./...
      # Note: Without quoting -coverprofile, it causes error "can't load package: package .txt" on windows-latest worker
      - run: go test -v -race '-coverprofile=coverage.txt' -covermode=atomic ./...
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
